# Site settings
site: webwithsk
title: Web With SK
keywords: ruby, ruby on rails, blog
description: >-
  Web With SK - Random findings while doing web development
lang: en-US
timezone:  India
repo: https://github.com/skarmakar/skarmakar.github.io # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Santanu Karmakar
  bio: Ruby On Rails, React Consultant @skarmakar
  picture: assets/images/profile.jpg 
  github: skarmakar # github username
  twitter: santanutt # twitter username
  linkedin: skarmakar # linkedin username
  email: skarmakar.personal@email.com # email adress


# URL settings
url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
